fn main() {
    windows::build!(
        Windows::Foundation::Numerics::{Vector2, Vector3},
        Windows::Foundation::TimeSpan,
        Windows::Foundation::Size,
        Windows::Graphics::SizeInt32,
        Windows::Graphics::DirectX::DirectXAlphaMode,
        Windows::Graphics::DirectX::DirectXPixelFormat,
        Windows::System::DispatcherQueueController,
        Windows::UI::Composition::{
            CompositionRoundedRectangleGeometry,
            CompositionShapeCollection,
            CompositionBrush,
            VisualCollection,
            AnimationIterationBehavior,
            CompositionBatchTypes,
            CompositionBorderMode,
            CompositionColorBrush,
            CompositionGeometry,
            CompositionShape,
            CompositionSpriteShape,
            Compositor,
            ContainerVisual,
            SpriteVisual,
            ShapeVisual,
            CompositionGraphicsDevice,
            CompositionContainerShape,
            CompositionSurfaceBrush,
            Vector3KeyFrameAnimation
        },
        Windows::UI::Composition::Desktop::DesktopWindowTarget,
        Windows::UI::Composition::CompositionDrawingSurface,
        Windows::UI::{Color, Colors, ColorHelper},
        Windows::Win32::System::SystemServices::{
            CreateDispatcherQueueController, BOOL, DQTYPE_THREAD_CURRENT, DQTAT_COM_NONE,
        },
        Windows::Win32::System::WinRT::ICompositorDesktopInterop,
        Windows::Win32::UI::WindowsAndMessaging::HWND,
        Microsoft::Graphics::Canvas::CanvasDrawingSession,
        Microsoft::Graphics::Canvas::CanvasDevice,
        Microsoft::Graphics::Canvas::Text::*,
        Microsoft::Graphics::Canvas::UI::Composition::*,
    );
}
